### ISSUE TITLE
UI voting power inconsistency with new unverified user

### ISSUE THREAD

**Issue by nsipplswezey** [liquidvote/web#30]
Look's like `this.state.voting_power` in `Your voting power for this bill is: &nbsp;{ this.state.voting_power || '...Loading...' }` at line
https://github.com/liquidvote/web/blob/master/src/Legislation/ConfirmVoteScreen.js#L115 may be deriving it's value from a different place than...

Wherever the `Menu` component is getting `votingPower`
```
let message = `Hello, ${first_name} (${votingPower})`
```
https://github.com/liquidvote/web/blob/6bfb11ab0f6e6cc4388fe5d1735383548bd38e82/src/Menu.js#L25

Screen screenshot.
![img_1453](https://user-images.githubusercontent.com/7946707/26950980-6e8416a4-4c54-11e7-9ad7-3e1f0bcf8674.PNG)

**Comment by dsernst** [comment]
So here's the relevant logic:

```jsx
<Text style={{ fontWeight: '700' }}>
  Your voting power for this bill is: &nbsp;{ this.state.voting_power || '...Loading...' }
</Text>
{ this.state.voting_power < this.props.votingPower &&
  <Text style={{ marginTop: 10 }}>
    This is less than your max voting power because some of your constituents have directly voted.
  </Text>
}
```

It is only checking for `<` (as assumed above). But changing that conditional to `!==` would not quite be right either because the text is specific to this `less than` situation.

So I'm gonna close this for now. 

But we might still want to add more explanation or something to make this clearer.
